config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_names => { sign_up: 'registration', sign_in: 'login', sign_out: 'logout'}
  #:controllers => {:registrations => "users/registrations"}
	resources :stocks
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stocks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :user

	validates :name, :unit_price, :interest, :duration,
		presence: {message: 'Field can\'t be blank'}
	validates :unit_price, length: {maximum: 9, message: 'Max length 9 symbols'}
	validates :unit_price, :interest, numericality: {message: 'You can use only numbers'}
	validates :interest, :duration, length: {maximum: 3, message: 'Max length 3 symbols'}
	validates :duration, numericality: { only_integer: true, message: 'You can use only numbers'}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :stocks
	
	validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable
	devise	:database_authenticatable, 
  		 	:registerable,
  		 	:rememberable, 
  		 	:trackable, 
  		 	:validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  #before_action :authenticate_user!, except: [:]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	before_filter :authenticate_user!, :except => [:index]

	#GET /stocks and GET /
	def index
		# @stocks = Stock.all
		if current_user
			@stocks = current_user.stocks.all
		else
			@stocks = Stock.all
		end
	end

	#GET /stocks/:id
	def show
		@stock = Stock.find(params[:id])
		date = @stock.created_at
		date = date.to_s(:db)
		date = date.split(' ')
		@start_date = date[0]
		year = @start_date.split('-')
		@start_year = year[0]

		@dividend_yield = []
		i = 1
		total = @stock.unit_price

		while (i < @stock.duration + 1) do
			total = (total / 100 ) * @stock.duration + total
			#puts i.to_s + ' total: ' + total.to_s
			@dividend_yield << {'year'=>i, 'total'=>total}
			i += 1
		end
		#puts @dividend_yield

	end

	#GET /stocks/new
	def new
		@stock = Stock.new
	end

	#POST /stocks
	def create
		if stock_params["unit_price"].scan(',')
			price = stock_params["unit_price"].split(',')
			price = price.join
		end
		params = stock_params
		params[:unit_price] = price

		@stock = current_user.stocks.new(params)

		if @stock.save
			redirect_to root_path, notice: 'Stock was successfully created.'
		else
			render 'new'
		end
	end

	private
	def stock_params
		params.require(:stock).permit(:name, :unit_price, :interest, :duration)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_add_stock_form.html.erb
<% if @stock.errors.any? %>
<div id="error_explanation">
  <ul>
    <% @stock.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<br>
<%= form_for :stock, url: stocks_path do |f| %>
<div class="form-group row">
  <%= f.label :'Name', class: 'col-2 col-form-label', for: 'stock-name' %>
  <div class="col-10">
   <%= f.text_field :name, 
   class: 'form-control', 
   placeholder: 'Insert stock name',  
   id: 'stock-price' %>
 </div>
</div>
<div class="form-group row">
  <%= f.label :'Stock price', class: 'col-2 col-form-label', for: 'stock-price' %>
  <div class="col-10">
   <%= f.text_field :unit_price, 
   class: 'form-control', 
   placeholder: 'Insert stock price in the format 0,00', 
   id: 'stock-price' %>
 </div>
</div>
<div class="form-group row">
  <%= f.label :'Interest', class: 'col-2 col-form-label', for: 'stock-interest' %>
  <div class="col-10">
   <%= f.text_field :interest, 
   class: 'form-control', 
   placeholder: 'Insert stock interest from 1 to 100',
   id: 'stock-interest' %>
 </div>
</div>
<div class="form-group row">
  <%= f.label :'Duration', class: 'col-2 col-form-label', for: 'stock-duration' %>
  <div class="col-10">
   <%= f.text_field :duration, 
   class: 'form-control', 
   placeholder: 'Insert duration in years',  
   id: 'stock-duration' %>
 </div>
</div>
<%= f.submit class: 'btn btn-primary'%>
<% end %>

app/views/layouts/_login_user_form.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field :password, autocomplete: "off", class: 'form-control',placeholder: 'Password' %>
    </div>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="form-group row">
      <%= f.label :remember_me, class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.check_box :remember_me %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
	<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="#">Stock Manager</a>
		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
			<div class="navbar-nav mr-auto">
				<%= link_to 'Home', root_path, :class => 'nav-item nav-link active' %>
				<% if user_signed_in?%>
					<%= link_to 'New Stock', new_stock_path, :class => 'nav-item nav-link' %>
				<% end %>
			</div>
			<div class="navbar-nav mt-2 mt-md-0">
				<% if user_signed_in?%>
					<span>Hello, <%= current_user.email %></span>
					<%= link_to 'Logout', destroy_user_session_path, :method => 'delete', :class => 'nav-item nav-link active' %>
				<% else %>
					<%= link_to 'Login', new_user_session_path, :class => 'nav-item nav-link active' %>
					<%= link_to 'Sign up', new_user_registration_path, :class => 'nav-item nav-link active' %>
				<% end %>
			</div>
		</div>
	</nav>

app/views/layouts/_new_stock_form.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field :password, autocomplete: "off", class: 'form-control',placeholder: 'Password' %>
    </div>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="form-group row">
      <%= f.label :remember_me, class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.check_box :remember_me %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

app/views/layouts/_stocks_show_table.html.erb
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Stock price</th>
      <th>Interest</th>
      <th>Duration</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <th scope="row"><%= stock.id %></th>
        <td><%= stock.name %></td>
        <td><%= number_to_currency(stock.unit_price / 100.0, 
        unit: "", 
        separator: ",") %></td>
        <td><%= number_to_percentage(stock.interest, precision: 0) %></td>
        <td><%= stock.duration %></td>
        <td><%= link_to 'Show stock', stock_path(stock) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>StockManager</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render 'layouts/navbar' %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/stocks/index.html.erb
<% if user_signed_in? %>
	<br>
	<h1>Stocks list</h1>
<%= render 'layouts/stocks_show_table' %>
<% else %>
	<br>
	<h1>Stock productivity calculator</h1>
<% end %>

app/views/stocks/new.html.erb
<br>
<h1>New Stock</h1>
<br>
<%= render 'layouts/add_stock_form' %>

app/views/stocks/show.html.erb
<br>
<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>
 
<p>
  <strong>Stock start price:</strong>
  <%= number_to_currency(@stock.unit_price / 100.0, 
        unit: "", 
        separator: ",") %>
</p>

<p>
  <strong>Interest:</strong>
  <%= number_to_percentage(@stock.interest, precision: 0) %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @stock.duration %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @start_date %>
</p>

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Year</th>
      <th>Stock price</th>
    </tr>
  </thead>
  <tbody>
      <% @dividend_yield.each do |stock| %>
      <tr>
        <td><%= stock['year'] %></td>
        <td><%= number_to_currency(stock['total'] / 100.0, 
        unit: "", 
        separator: ",") %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<br>